Run npm install
npm error code ENOENT
npm error syscall open
npm error path /home/runner/work/jee-mock-simulator/jee-mock-simulator/package.json
npm error errno -2
npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open '/home/runner/work/jee-mock-simulator/jee-mock-simulator/package.json'
npm error enoent This is related to npm not being able to find a file.
npm error enoent
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2026-01-06T14_18_37_126Z-debug-0.log
Error: Process completed with exit code 254.
